=== Mikram1/Katat-codewars/XML/HW3/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="brewery_catalogue">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="note" type="xs:string"/>
				<xs:element name="cdatasection" type="xs:string"/>
				<xs:element name="date" type="xs:date"/>
				
				<!-- countries-element, with only globally defined subelements. -->
				<xs:element name="countries">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="country" type="gCountry" minOccurs="1" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<!-- beer_types-element, with only locally defined subelements. -->
				<xs:element name="beer_types">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="beer_type" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string"/>
										<xs:element name="explanation" type="xs:string"/>
										<!-- this is an optional element. -->
										<xs:element name="personal_note" type="xs:string" minOccurs="0"/>
									</xs:sequence>
								<xs:attribute name="beerID" type="xs:ID" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
			</xs:sequence>
		</xs:complexType>
		
	<!-- A key for the different countries. -->
	<xs:key name="KCountry">
		<xs:selector xpath="countries/country"/>
		<xs:field xpath="@countryID"/>
	</xs:key>
	
	<!-- A key for the different beer types. -->
	<xs:key name="KBeer_type">
		<xs:selector xpath="beer_types/beer_type"/>
		<xs:field xpath="@beerID"/>
	</xs:key>
	
	</xs:element>
	
	<xs:complexType name="gCountry">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="breweries">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="brewery" type="gBrewery" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="countryID" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="gBrewery">
		<xs:sequence>
			<xs:group ref="breweryElements" minOccurs="1" maxOccurs="1"/>
			<xs:element name="beers">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="beer" type="gBeer" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="gBeer">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<!-- ks. https://www.w3schools.com/xml/schema_complex_text.asp -->
			<xs:element name="type">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="typeRef" type="xs:IDREF" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="alcohol_content" type="xs:string"/>
		</xs:sequence>
		<!-- An optional attribute. And a personal opinion. -->
		<xs:attribute name="is_delicious" type="xs:boolean"/>
	</xs:complexType>
	
	<!-- The simple elements of brewery that must occur only 1 time. -->
	<xs:group name="breweryElements">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="founding_city" type="xs:string"/>
			<!-- The element "founding_year"'s value is restricted to 1300-2020. -->
			<xs:element name="founding_year">
				<xs:simpleType>
					<xs:restriction base="xs:positiveInteger">
						<xs:minInclusive value="1300"/>
						<xs:maxInclusive value="2020"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	
</xs:schema>

=== Mikram1/Katat-codewars/XML/HW5/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Made by Mikko Toitturi. -->	
<brewery_catalogue>
	<!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="data.xsd" -->
	<note>The goal of this document is to list different countries' breweries and their signature types of beer. Current status is: a work in progress.</note>
	<cdatasection> <![CDATA[
			<p>Here's a code to count the number of beers for a later stage: </p>
			document.writeln(<p>"Current number of beers is: document.getElementsByTagName("beer").length"</p>
			]]>
	</cdatasection>
	<date>2020-04-03</date>
	<countries>
		<country countryID="CZE">
			<name>Czech Republic</name>
			<breweries>
				<brewery>
					<name>Pilsner Urquell Brewery</name>
					<founding_city>Plzeň</founding_city>
					<founding_year>1842</founding_year>
					<beers>
						<beer>
							<name>Pilsner Urquell</name>
							<type typeRef="PaleLager">Pale lager</type>
							<alcohol_content>4,4 %</alcohol_content>
						</beer>
						<beer is_delicious="true">
							<name>Gambrinus Original</name>
							<type typeRef="PaleLager">Pale lager</type>
							<alcohol_content>4,3 %</alcohol_content>
						</beer>
						<beer is_delicious="true">
							<name>Kozel Černý</name>
							<type typeRef="DarkLager">Dark lager</type>
							<alcohol_content>3,8 %</alcohol_content>
						</beer>
					</beers>
				</brewery>
				<brewery>
					<name>Royal Brewery of Krušovice</name>
					<founding_city>Krušovice</founding_city>
					<founding_year>1581</founding_year>
					<beers>
						<beer>
							<name>Krušovice 10</name>
							<type typeRef="PaleDraught">Pale draught beer</type>
							<alcohol_content>4,2 %</alcohol_content>
						</beer>
					</beers>
				</brewery>
			</breweries>
		</country>
		<country countryID="FIN">
			<name>Finland</name>
			<breweries>
				<brewery>
					<name>Olvi Brewery</name>
					<founding_city>Iisalmi</founding_city>
					<founding_year>1878</founding_year>
					<beers>
						<beer is_delicious="true">
							<name>Sandels</name>
							<type typeRef="PaleDraught">Pale draught beer</type>
							<alcohol_content>4,7 %</alcohol_content>
						</beer>
					</beers>
				</brewery>
				<brewery>
					<name>Hartwall Brewery</name>
					<founding_city>Sortavala</founding_city>
					<founding_year>1836</founding_year>
					<beers>
						<beer>
							<name>Karjala III</name>
							<type typeRef="PaleLager">Pale lager</type>
							<alcohol_content>4,6 %</alcohol_content>
						</beer>
						<beer>
							<name>Lapin kulta</name>
							<type typeRef="PaleLager">Pale lager</type>
							<alcohol_content>4,5 %</alcohol_content>
						</beer>
					</beers>
				</brewery>
			</breweries>
		</country>
	</countries>
	<beer_types>
	<!-- The types will increase as more beers are added. -->
		<beer_type beerID="PaleLager">
			<name>Pale Lager</name>
			<explanation>https://en.wikipedia.org/wiki/Pale_lager</explanation>
			<personal_note>I did this just to accomplish the second homework requiring an 
			absence of an element</personal_note>
		</beer_type>
		<beer_type beerID="PaleDraught">
			<name>Pale Draught</name>
			<explanation>https://en.wikipedia.org/wiki/Draught_beer</explanation>
		</beer_type>
		<beer_type beerID="DarkLager">
			<name>Dark Lager</name>
			<explanation>https://en.wikipedia.org/wiki/Lager#Dark_lager</explanation>
		</beer_type>
	</beer_types>
</brewery_catalogue>
